### ISSUE TITLE
要補的 flags

### ISSUE THREAD

**Issue by lucemia** [livingbio/ffmpeg-gl-transition#7]
https://github.com/transitive-bullshit/ffmpeg-gl-transition/blob/master/Dockerfile

要補一些 flag

**Comment by lucemia** [comment]
`--enable-opengl --enable-filter=gltransition --extra-libs='-lGLEW -lglfw -ldl' `

**Comment by benwu95** [comment]
https://github.com/livingbio/ffmpeg-gl-transition/blob/c23ec909254566da497049d66b59cb78c6150484/Dockerfile#L371-L373

**Comment by lucemia** [comment]
已經加了
